<?php
/*/**
 * Created by PhpStorm.
 * User: b0dun
 * Date: 18.09.2017
 * Time: 21:34
 */
/*$Data = str_getcsv( 'Марка;Модель;
Peugeot;1007;
Alfa Romeo;147;
Alfa Romeo;156;
Alfa Romeo;159;
Mercedes-Benz;190;
BMW;1-series;
Peugeot;2008;
Peugeot;206;
Peugeot;207;
Peugeot;208;
VAZ;21099;
Mercedes-Benz;220;
Jeep;2500;
BMW;2-series;
Mazda;3;
MG;3;
Chrysler;300;
Peugeot;3008;
Peugeot;301;
Peugeot;307;
Peugeot;308;
Peugeot;308 SW;
Mazda;323;
MG;350;
BMW;3-series;
Peugeot;4007;
Peugeot;406;
Peugeot;407;
Peugeot;408;
Saab;42616;
Saab;42618;
Saab;42980;
Saab;42981;
Saab;42983;
Rover;45;
BMW;4-series;
MG;5;
Fiat;500;
Peugeot;5008;
Fiat;500L;
Peugeot;508;
Geely;515;
MG;550;
Maybach;57;
BMW;5-series;
MG;6;
Peugeot;607;
Maybach;62;
Lifan;620;
Mazda;626;
BMW;6-series;
MG;7;
Porsche;718;
BMW;7-series;
Peugeot;807;
Volvo;850;
Porsche;911;
Porsche;912;
Porsche;918;
Mazda;929;
Saab;9-2X;
Saab;09.мар;
Saab;9-3X;
Saab;9-4X;
Saab;9-7X;
Audi;A1;
Chery;A13;
Chery;A15;
Chery;A19;
Audi;A2;
Chery;A3;
Audi;A3;
Audi;A4;
Chery;A5;
Audi;A5;
Chery;A6;
Audi;A6;
Audi;A6 Avant;
Audi;A7;
Audi;A8;
GMC;Acadia;
GMC;Acadia Denali;
Hyundai;Accent;
Honda;Accord;
Honda;Accord Crosstour;
Mercedes-Benz;A-Class;
Ssangyong;Actyon;
Opel;Adam;
Holden;Adventra;
Fiat;Albea;
Seat;Alhambra;
Mazda;Allegro;
Nissan;Almera;
Seat;Altea;
Nissan;Altima;
Suzuki;Alto;
Volkswagen;Amarok;
Mercedes-Benz;AMG GT;
Opel;Ampera;
Chery;Amulet;
Vauxhall;Antara;
Opel;Antara;
Bentley;Arnage;
Chery;Arrizo 3;
Chery;Arrizo 5;
Chery;Arrizo 7;
Mazda;Astina;
Holden;Astra;
Vauxhall;Astra;
Opel;Astra;
Mitsubishi;ASX;
Mazda;Atenza;
Toyota;Auris;
Toyota;Auris Touring Sports;
Toyota;Avalon;
Dodge;Avenger;
Toyota;Avensis;
Chevrolet;Aveo;
Lincoln;Aviator;
Mazda;Axela;
Toyota;Aygo;
Mazda;AZ-Offroad;
Bentley;Azure;
Mazda;AZ-Wagon;
Mercedes-Benz;B200;
Besturn;B30;
Besturn;B50;
Besturn;B70;
Subaru;B9 Tribeca;
Besturn;B90;
Suzuki;Baleno;
Holden;Barina;
Holden;Barina Spark;
Mercedes-Benz;B-Class;
Volkswagen;Beetle;
Holden;Berlina;
Citroen;Berlingo;
FAW;Besturn B50;
FAW;Besturn B70;
FAW;Besturn X80;
Mazda;Biante;
Peugeot;Bipper;
Lincoln;Blackwood;
Chevrolet;Blazer;
Cadillac;BLS;
Ford;B-Max;
Chevrolet;Bolt;
Mazda;Bongo;
Volkswagen;Bora;
Geely;Borui;
Porsche;Boxster;
Fiat;Bravo;
Mazda;B-Series;
Mazda;BT-50;
Citroen;C3;
Citroen;C3 Picasso;
Volvo;C30;
Great Wall;C30;
Citroen;C4;
Citroen;C4 Cactus;
Citroen;C4 Picasso;
Citroen;C5;
Great Wall;C50;
Citroen;C6;
Volvo;C70;
Volkswagen;Caddy;
Holden;Calais;
Dodge;Caliber;
Toyota;Camry;
GMC;Canyon;
Mazda;Capella;
Holden;Caprice;
Holden;Captiva;
Chevrolet;Captiva;
Renault;Captur;
Dodge;Caravan;
Volkswagen;Caravelle;
Kia;Carens;
Mitsubishi;Carisma;
Kia;Carnival;
Mazda;Carol;
Holden;Cascada;
Porsche;Cayenne;
Porsche;Cayman;
Volkswagen;CC;
Mercedes-Benz;C-Class;
Citroen;C-Crosser;
Kia;Cee\'d;
Kia;Cee\'d Sportswagon;
Citroen;C-Elysee;
Kia;Cerato;
Dodge;Challenger;
ZAZ;Chance;
Dodge;Charger;
Jeep;Cherokee;
Mercedes-Benz;Citan;
Honda;Civic;
Geely;CK;
Acura;CL;
Mercedes-Benz;CLA-Class;
Mercedes-Benz;CL-Class;
Renault;Clio;
Renault;Clio Break;
Mercedes-Benz;CLK-Class;
Mercedes-Benz;CLS-Class;
Holden;Clubsport;
Ford;C-Max;
Ford;C-Max Hybrid;
Chevrolet;Cobalt;
Holden;Colorado;
Holden;Colorado 7;
Mitsubishi;Colt;
Opel;Combo C;
Opel;Combo D;
Jeep;Commander;
Holden;Commodore;
Jeep;Compass;
Lincoln;Continental;
Mini;Cooper;
Seat;Cordoba;
Toyota;Corolla;
Opel;Corsa;
Mini;Countryman;
Maserati;Coupe;
Chery;Cowin;
Holden;Crewman;
Fiat;Croma;
Honda;Crosstour;
Holden;Cruze;
Chevrolet;Cruze;
Honda;CR-V;
Lexus;CT;
Cadillac;CTS;
Mazda;CX-3;
Mazda;CX-5;
Mazda;CX-7;
Mazda;CX-9;
Citroen;C-Zero;
Aston Martin;DB9;
Land Rover;Defender;
Lancia;Delta;
Mazda;Demio;
Land Rover;Discovery;
DeLorean;DMC-12;
Fiat;Doblo;
Renault;Dokker;
Geely;Dorsett;
Citroen;DS3;
Citroen;DS4;
Citroen;DS5;
Fiat;Ducato;
Dodge;Durango;
Dacia;Duster;
Renault;Duster;
Renault;Duster Oroch;
Chery;E3;
Chery;E5;
Chery;Eastar;
Geely;EC8;
Mercedes-Benz;E-Class;
Mercedes-Benz;E-Class Wagon;
Ford;EcoSport;
Ford;Edge;
Mersedes;E-klass;
Hyundai;Elantra;
Chery;Elara;
Citroen;Elysee;
Geely;Emgrand 7;
Geely;Emgrand 8;
Geely;Emgrand EC7;
Geely;Emgrand EC718;
Geely;Emgrand EC8;
Geely;Emgrand X7;
GMC;Envoy;
GMC;Envoy Denali;
Chery;Envy;
Holden;Epica;
Chevrolet;Epica;
Hyundai;Equus;
Lexus;ES;
Cadillac;Escalade;
Cadillac;Escalade EXT;
Ford;Escape;
Ford;Escort;
Renault;Espace;
Daewoo;Espero;
Jaguar;E-Type;
Volkswagen;e-up!;
Chevrolet;Evanda;
Infiniti;EX;
Geely;EX7;
Seat;Exeo;
Peugeot;Expert;
Ford;Explorer;
Ford;Explorer Sport Trac;
BYD;F3;
BYD;F5 Suri;
BYD;F6;
BYD;F7;
Skoda;Fabia;
Chery;Face;
Mazda;Familia;
Ford;Fiesta;
Fiat;Fiorino;
Honda;Fit;
Ford;Five Hundred;
Mazda;Flair;
Renault;Fluence;
Bentley;Flying Spur;
Ford;Focus;
Subaru;Forester;
Smart;Forfour;
ZAZ;Forza;
Jaguar;F-PACE;
Land Rover;Freelander;
Fiat;Freemont;
Scion;FR-S;
Honda;FR-V;
Jaguar;F-Type;
Ford;Fusion;
Infiniti;FX;
Infiniti;G Sedan;
BYD;G3;
BYD;G3R;
BYD;G5;
Mitsubishi;Galant;
Ford;Galaxy;
Lamborghini;Gallardo;
Geely;GC2;
Geely;GC5;
Geely;GC6;
Geely;GC7;
Geely;GC9;
Mercedes-Benz;G-Class;
Hyundai;Genesis;
Ravon;Gentra;
Daewoo;Gentra;
Hyundai;Getz;
Maserati;Ghibli;
Rolls-Royce;Ghost;
Alfa Romeo;Giulietta;
Mercedes-Benz;GLA-Class;
Mercedes-Benz;GLC-Class;
Mercedes-Benz;GL-Class;
Geely;Gleagle;
Mercedes-Benz;GLE-Class;
Mercedes-Benz;GLK-Class;
Mercedes-Benz;GLS-Class;
Datsun;Go;
Datsun;Go+;
Volkswagen;Golf;
Volkswagen;Golf Variant;
Maserati;Gran Turismo;
Maserati;GranCabrio;
Dodge;Grand Caravan;
Jeep;Grand Cherokee;
Ford;Grand C-Max;
Hyundai;Grand Santa Fe;
Renault;Grand Scenic;
Chery;Grand Tiggo;
Suzuki;Grand Vitara;
Chrysler;Grand Voyager;
Fiat;Grande Punto;
Hyundai;Grandeur;
Mitsubishi;Grandis;
Holden;Grange;
Maserati;GranSport;
Lada;Granta;
Lexus;GS;
Holden;GTS;
Lexus;GX;
Geely;GX2;
Geely;GX7;
Geely;GX9;
Hummer;H1;
Hyundai;H-1;
Hummer;H2;
Hummer;H2 SUT;
Hummer;H3;
Hummer;H3T;
Geely;Haijing;
Geely;Haoqing;
Great Wall;Haval H1;
Great Wall;Haval H2;
Great Wall;Haval H3;
Great Wall;Haval H5;
Great Wall;Haval H6;
Great Wall;Haval H7;
Great Wall;Haval H8;
Great Wall;Haval H9;
Great Wall;Haval M2;
Great Wall;Haval M4;
Chevrolet;HHR;
Toyota;Highlander;
Toyota;Hilux;
Great Wall;Hover;
Great Wall;Hover 5;
Honda;HR-V;
Lexus;HS;
Hyundai;i10;
Hyundai;i20;
Hyundai;i30;
Hyundai;i35;
Hyundai;i40;
Scion;iA;
Seat;Ibiza;
Scion;iM;
Subaru;Impreza;
Honda;Insight;
Holden;Insignia;
Vauxhall;Insignia;
Opel;Insignia;
Honda;Integra;
Scion;iQ;
Lexus;IS;
Hyundai;ix20;
Hyundai;ix25;
Hyundai;ix35;
Hyundai;ix55;
JAC Motors;J5;
JAC Motors;J6;
Honda;Jazz;
Volkswagen;Jetta;
GMC;Jimmy;
Geely;Jingang;
Dodge;Journey;
Nissan;Juke;
Citroen;Jumpy;
Geely;K17;
Renault;Kadjar;
Lada;Kalina;
Chevrolet;Kalos;
Daewoo;Kalos;
Renault;Kangoo;
Honda;Karisma;
ZNEN;Koala;
Renault;Koleos;
Ssangyong;Korando;
Ford;Kuga;
Renault;Kwid;
Ssangyong;Kyron;
Mitsubishi;L200;
Chevrolet;Lacetti;
Renault;Laguna;
Mitsubishi;Lancer;
Toyota;Land Cruiser;
ZAZ;Lanos;
Chevrolet;Lanos;
Daewoo;Lanos;
Mazda;Lantis;
Lada;Largus;
Renault;Latitude;
Geely;LC;
Geely;LC Cross;
Nissan;LEAF;
Subaru;Legacy;
Daewoo;Leganza;
Honda;Legend;
Seat;Leon;
Maserati;Levante;
Lexus;LFA;
Jeep;Liberty;
Fiat;Linea;
Renault;Lodgy;
Dacia;Lodgy;
Renault;Logan;
Dacia;Logan;
Land Rover;LR2;
Land Rover;LR3;
Land Rover;LR4;
Lincoln;LS;
Lexus;LS;
Lexus;LX;
Lancia;Lybra;
Infiniti;M;
Chery;M 11;
Chery;M11;
Porsche;Macan;
Porsche;Macan Turbo;
Kia;Magentis;
Holden;Malibu;
Chevrolet;Malibu;
Lincoln;Mark;
Jaguar;Mark 2;
Lincoln;Mark LT;
Renault;Master;
Daihatsu;Materia;
Toyota;Matrix;
Hyundai;Matrix;
Ford;Maverick;
Nissan;Maxima;
Mazda;MAZDA2;
Mazda;MAZDA3;
Mazda;MAZDA5;
Mazda;MAZDA6;
Mazda;MAZDA8;
Mazda;MAZDASPEED3;
Mazda;MAZDASPEED6;
Maserati;MC12;
Mercedes-Benz;M-Class;
Acura;MDX;
Renault;Megane;
Renault;Megane Estate;
Geely;Meiri;
Chevrolet;Meriva;
Vauxhall;Meriva;
Opel;Meriva;
Mercedes-Benz;Metris;
MG;MG 3;
MG;MG 5;
MG;MG 6;
MG;MG 7;
Nissan;Micra;
Datsun;mi-DO;
Mazda;Millenia;
Alfa Romeo;Mito;
Geely;MK;
Geely;MK Cross;
Lincoln;MKC;
Lincoln;MKS;
Lincoln;MKT;
Lincoln;MKX;
Lincoln;MKZ;
Mercedes-Benz;ML Class;
Honda;Mobilio;
Tesla;Model S;
Tesla;Model X;
Renault;Modus;
Kia;Mohave;
Opel;Mokka;
Ford;Mondeo;
Mazda;MPV;
Bentley;Mulsanne;
Fiat;Multipla;
Volkswagen;Multivan;
Nissan;Murano;
GMC;MV1;
Hummer;MV-1;
Mazda;MX-5 Miata;
FAW;N5;
FAW;N7;
Nissan;Navara;
Lincoln;Navigator;
Citroen;Nemo;
Dodge;Neon;
Renault;New Logan;
Daewoo;Nexia;
Dodge;Nitro;
Chevrolet;Niva;
Nissan;Note;
Chevrolet;Nubira;
Daewoo;Nubira;
Nissan;NV200;
Lexus;NX;
Skoda;Octavia;
Skoda;Octavia Combi;
Honda;Odyssey;
Opel;Omega;
Datsun;On-Do;
Kia;Opirus;
Kia;Optima;
Chevrolet;Orlando;
Subaru;Outback;
Mitsubishi;Outlander;
Chrysler;Pacifica;
Mitsubishi;Pajero;
Porsche;Panamera;
Geely;Panda;
Fiat;Panda;
Peugeot;Partner;
Volkswagen;Passat;
Nissan;Pathfinder;
Jeep;Patriot;
UAZ;Patriot;
Nissan;Patrol;
Volkswagen;Phaeton;
Rolls-Royce;Phantom;
Lancia;Phedra;
Kia;Picanto;
Honda;Pilot;
Volkswagen;Polo;
Volkswagen;Polo Sedan;
Toyota;Prado;
Mazda;Premacy;
Nissan;Primera;
Lada;Priora;
Toyota;Prius;
Mazda;Protege;
Chrysler;PT Cruiser;
Nissan;Pulsar;
Renault;Pulse;
Fiat;Punto;
Audi;Q3;
Infiniti;Q45;
Audi;Q5;
Infiniti;Q50;
Infiniti;Q60;
Audi;Q7;
Nissan;Qashqai;
Maserati;Quattroporte;
Fiat;Qubo;
Kia;Quoris;
Infiniti;QX56;
Infiniti;QX60;
Infiniti;QX80;
Ravon;R2;
Ravon;R3;
Ravon;R4;
Dodge;Ram 1500;
Dodge;Ram Van;
Land Rover;Range Rover;
Land Rover;Range Rover Evoque;
Land Rover;Range Rover Sport;
Land Rover;Range Rover Vogue;
Skoda;Rapid;
Skoda;Rapid Spaceback;
Aston Martin;Rapide;
Toyota;RAV4;
Lexus;RC;
Mercedes-Benz;R-Class;
Acura;RDX;
Datsun;redi-GO;
Jeep;Renegade;
Suzuki;Reno;
Ssangyong;Rexton;
Honda;Ridgeline;
Kia;Rio;
Acura;RLX;
Holden;Rodeo;
Ssangyong;Rodius;
Nissan;Rogue;
Skoda;Roomster;
Lexus;RX;
Mazda;RX-8;
Volvo;S40;
Audi;S5;
JAC Motors;S5;
BYD;S6;
Volvo;S60;
Audi;S7;
Volvo;S70;
Audi;S8;
Volvo;S80;
Volvo;S90;
GMC;Safari;
Renault;Safrane;
IKCO;Samand LX;
IKCO;Samand SE;
Lada;Samara;
Renault;Samsung SM5;
Dacia;Sandero;
Renault;Sandero;
Hyundai;Santa Fe;
GMC;Savana 1500;
GMC;Savana 2500;
GMC;Savana 3500;
Lexus;SC;
Geely;SC3;
Geely;SC5;
Geely;SC7;
Renault;Scala;
Renault;Scenic;
Mercedes-Benz;S-Class;
Mazda;Scrum;
Fiat;Scudo;
Chrysler;Sebring;
ZAZ;Sens;
Nissan;Sentra;
Volkswagen;Sharan;
Kia;Shuma;
Volga;Siber;
Fiat;Siena;
GMC;Sierra 1500;
GMC;Sierra 2500;
GMC;Sierra 3500;
Vauxhall;Signum;
Opel;Signum;
Rolls-Royce;Silver Shadow;
Daihatsu;Sirion;
Geely;SL;
Mercedes-Benz;SL-Class;
Mercedes-Benz;SLK-Class;
Mercedes-Benz;SLR McLaren;
Mercedes-Benz;SLS AMG;
Ford;S-Max;
Hyundai;Solaris;
Hyundai;Sonata;
GMC;Sonoma;
Kia;Sorento;
Kia;Soul;
Mazda;SP23;
Mazda;SP25;
Mitsubishi;Space Star;
Mitsubishi;Space Wagon;
Chevrolet;Spark;
Mazda;Spiano;
Saab;Sport;
Kia;Sportage;
Mercedes-Benz;Sprinter;
Maserati;Spyder;
Cadillac;SRX;
Hyundai;Starex;
Holden;Statesman;
Ssangyong;Stavic;
Renault;Stepway;
Honda;Stream;
Dodge;Stretch Limo;
Volvo;Stretch Limo;
Lincoln;Stretch Limo;
Toyota;Stretch Limo;
Mercedes-Benz;Stretch Limo;
Hummer;Stretch Limo;
Holden;Stretch Limo;
Cadillac;STX;
Kia;Stylus;
Jaguar;S-Type;
GMC;Suburban;
Nissan;Sunny;
Skoda;Superb;
Skoda;Superb Combi;
Holden;SV6;
Suzuki;Swift;
Suzuki;SX4;
Geely;SX7;
Renault;Symbol;
Bentley;T2;
Toyota;Tacoma;
Daewoo;Tacuma;
Chevrolet;Tacuma;
Chevrolet;Tahoe;
Renault;Talisman;
Porsche;Targa;
Ford;Taurus;
Scion;tC;
Nissan;Teana;
Fiat;Tempra;
Daihatsu;Terios;
Hyundai;Terracan;
GMC;Terrain;
Nissan;Terrano;
Renault;Thalia;
Lancia;Thema;
Lancia;Thesis;
Chery;Tiggo;
Chery;Tiggo 3;
Chery;Tiggo 5;
Holden;Tigra;
Volkswagen;Tiguan;
Nissan;Tiida;
Fiat;Tipo;
Acura;TL;
Seat;Toledo;
Renault;Tondar;
Volkswagen;Touareg;
Volkswagen;Touran;
Ford;Tourneo;
Lincoln;Town Car;
Chevrolet;Tracker;
Renault;Trafic;
Chevrolet;Trailblazer;
Hyundai;Trajet;
Ford;Transit Connect;
Volkswagen;Transporter;
Holden;Trax;
Subaru;Tribeca;
Mazda;Tribute;
Acura;TSX;
Hyundai;Tucson;
Renault;Twingo;
Geely;TX4;
Volvo;V40;
FAW;V5;
Volvo;V50;
Volvo;V60;
Volvo;V70;
Volvo;V90;
Mercedes-Benz;Valente;
Mercedes-Benz;Vaneo;
Mercedes-Benz;V-Class;
Saab;Vector;
Holden;Vectra;
Vauxhall;Vectra;
Opel;Vectra;
Renault;Vel Satis;
Kia;Venga;
Toyota;Venza;
Hyundai;Veracruz;
Hyundai;Veracruze;
Mazda;Verisa;
Toyota;Verso;
Lada;Vesta;
Mercedes-Benz;Viano;
Pontiac;Vibe;
ZAZ;Vida;
Suzuki;Vitara;
Mercedes-Benz;Vito;
Holden;Viva;
Opel;Vivaro;
Vauxhall;Vivaro;
Great Wall;Voleex;
Holden;Volt;
Chevrolet;Volt;
Chrysler;Voyager;
Mazda;VX-1;
Jeep;Wrangler;
BMW;X1;
Great Wall;X200;
BMW;X3;
BMW;X4;
BMW;X5;
Lifan;X50;
Landwind;X6;
BMW;X6;
Lifan;X60;
Besturn;X80;
Scion;xA;
Scion;xB;
Volvo;XC60;
Volvo;XC70;
Volvo;XC90;
Scion;xD;
Jaguar;XE;
Mazda;Xedos 6;
Mazda;Xedos 9;
Jaguar;XF;
Jaguar;XJ;
Jaguar;XJR;
Jaguar;XK;
Seat;X-Perience;
Lada;Xray;
Citroen;Xsara;
Citroen;Xsara Picasso;
Nissan;X-Trail;
Jaguar;X-Type;
Subaru;XV Crosstrek;
Toyota;Yaris;
Skoda;Yeti;
Lancia;Ypsilon;
Geely;Yuanjin;
GMC;Yukon;
GMC;Yukon Denali;
GMC;Yukon XL;
GMC;Yukon XL Denali;
Holden;Zafira;
Vauxhall;Zafira;
Opel;Zafira;
Lincoln;Zephyr;
Geely;Ziyoujian;
Renault;Zoe;', "\n" ); //parse the rows

$csvData = [];
foreach ( $Data as &$Row )
{
	$csvData[] = str_getcsv( $Row, ";" ); //parse the items in rows
}

function DB_connect() {
	$dsn      = 'mysql:dbname=test;host=127.0.0.1';
	$user     = 'root';
	$password = '';

	try {
		$dbh = new PDO( $dsn, $user, $password );

		return $dbh;
	} catch ( PDOException $e ) {
		return 'Connection failed: ' . $e->getMessage();
	}
}

foreach ($csvData as $data){
	echo $data[0].'  '. $data[1]. '<br>';
//	$sth = DB_connect()->prepare( "INSERT INTO cars(car_brand,car_model) VALUE (:car_brand, :car_model)" );
//	$sth->execute( array( ':car_brand' => $data[0], ':car_model' => $data[1], ) );
//	$array[] = DB_connect()->lastInsertId();
}

echo json_encode( $array );*/

//$client = new HttpClient('http://1cconnect.uberlin.com.ua:4080/');

//
//echo $client->post('/crm_test/hs/uberlin', array(
//	'username' => 'SiteUberlin',
//	'password' => 'GU1me9qi'
//));
//
//$url = '193.169.245.164:4080/crm_test/hs/uberlin/check-email';
//$data = array(
//	'headers' => array(
//		'Authorization' => 'Basic ' . base64_encode( 'SiteUberlin' . ':' . 'GU1me9qi' )
//	));
//
//function httpPost($url, $data)
//{
//	$curl = curl_init($url);
//	curl_setopt($curl, CURLOPT_POST, true);
//	curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
//	curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
//	$response = curl_exec($curl);
//	curl_close($curl);
//	return $response;
//}
//
//echo httpPost($url,$data);
$i=1;
$file['FrontPage']       = "1";
	$file['Kategory']    = "1";
	$file['TechMark']    = "1";
	$file['TechNumber']  = "1";
	$file['polis']       = "1";
@$response->result = 'ok';
foreach ($file as $item){
	if($response->result == 'ok'){
		echo ' doc_'.$i;
		$i++;
	}
}
